image: rikorose/gcc-cmake

stages:
  - build

compile-software:
  stage: build
  variables:
    CC: gcc
    CXX: g++
  script:
    - cmake -H. -Bbuild
    - cmake --build build -- -j3
  artifacts:
    paths:
      - ./build/ants
      - ./build/ants_test

test-software:
  stage: test
  script:
    script:
      - cmake -H. -Bbuild
      - cmake --build build -- -j3 --target ants_test
      - ./build/ants_test