image: rikorose/gcc-cmake

stages:
  - build

compile-software:
  stage: build
  variables:
    CC: gcc
    CXX: g++
  script:
    - mkdir cmake-build && cd cmake-build
    - cmake --target ants ../ -o ants